version: 2

models:
  - name: boardgame_years
    description: >
      Aggregated table of all boardgames organized by published year
      giving the details about total number of boardgames and percentage
  - name: boardgame_avg_prices
    description: >
      Aggregated table of all boardgames prices organized by price ranges.
  - name: fact_boardgames
    description: >
      Boardgames records from boardgamegeek website with information about ranking, name, published year, rating, number of voters, description.
      Each boardgame is uniquely identified by id.
      The table contains also information about the prices that boardgames are available on stores with the average price and price range data.